services:

  postgres:
    image: postgres:17
    container_name: investment-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - investment-network


  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: investment-app
    restart: "no"

    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      LOG_LEVEL: ${LOG_LEVEL}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      TINVEST_TOKEN: ${TINVEST_TOKEN}

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - investment-network


networks:
  investment-network:
    driver: bridge